// packages/react/src/core/AeroSky.tsx
import type { CSSProperties, ReactNode } from "react";
import { useAeroTheme } from "../AeroThemeProvider";
import type { AeroTheme } from "../theme";
import { Celestial } from "./Celestial";
import { Stars } from "./Stars";
import { BubbleField } from "./BubbleField";

export interface AeroSkyProps {
  theme?: AeroTheme;
  bubbles?: boolean;
  bubbleCount?: number;
  seed?: number;
  celestial?: boolean;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

export function AeroSky({
  theme,
  bubbles,
  bubbleCount = 14,
  seed = 1,
  celestial = true,
  className = "",
  style,
  children,
}: AeroSkyProps) {
  const ctx = useAeroTheme();
  const t = theme ?? ctx.theme ?? "morning";
  const showBubbles = bubbles !== undefined ? bubbles : ctx.bubbles !== false;

  return (
    <div className={`aero-sky theme-${t} ${className}`.trim()} style={style} data-screen-label={`sky-${t}`}>
      {celestial && <Celestial theme={t} />}
      {t === "night" && <Stars seed={seed + 5} />}
      {showBubbles && <BubbleField count={bubbleCount} seed={seed} />}
      <div style={{ position: "relative", zIndex: 1, height: "100%", boxSizing: "border-box" }}>{children}</div>
    </div>
  );
}

// packages/vue/src/core/AeroSky.vue
<script setup lang="ts">
import { computed } from "vue";
import { useAeroTheme } from "../context";
import type { AeroTheme } from "../theme";
import Celestial from "./Celestial.vue";
import Stars from "./Stars.vue";
import BubbleField from "./BubbleField.vue";

const props = withDefaults(
  defineProps<{
    theme?: AeroTheme;
    bubbles?: boolean;
    bubbleCount?: number;
    seed?: number;
    celestial?: boolean;
  }>(),
  { bubbleCount: 14, seed: 1, celestial: true },
);

const ctx = useAeroTheme();
const theme = computed<AeroTheme>(() => props.theme ?? ctx.value.theme ?? "morning");
const showBubbles = computed(() => (props.bubbles !== undefined ? props.bubbles : ctx.value.bubbles !== false));
</script>

<template>
  <div class="aero-sky" :class="`theme-${theme}`" :data-screen-label="`sky-${theme}`">
    <Celestial v-if="celestial" :theme="theme" />
    <Stars v-if="theme === 'night'" :seed="seed + 5" />
    <BubbleField v-if="showBubbles" :count="bubbleCount" :seed="seed" />
    <div :style="{ position: 'relative', zIndex: 1, height: '100%', boxSizing: 'border-box' }">
      <slot />
    </div>
  </div>
</template>
