// packages/vue/src/display/Accordion.vue
<script setup lang="ts">
import { ref } from "vue";

export interface AccordionItem {
  title: string;
  body: string;
}

const props = withDefaults(defineProps<{ items: AccordionItem[]; defaultOpen?: number }>(), { defaultOpen: 0 });
const open = ref(props.defaultOpen);

function toggle(i: number) {
  open.value = open.value === i ? -1 : i;
}
</script>

<template>
  <div class="aero-accordion">
    <div v-for="(it, i) in items" :key="i" class="aero-acc-item" :data-open="open === i">
      <div class="aero-acc-head" @click="toggle(i)">
        <span>{{ it.title }}</span>
        <span class="aero-acc-caret">▼</span>
      </div>
      <div v-if="open === i" class="aero-acc-body">{{ it.body }}</div>
    </div>
  </div>
</template>

// packages/react/src/display/Accordion.tsx
import { useState } from "react";
import type { ReactNode } from "react";

export interface AccordionItem {
  title: ReactNode;
  body: ReactNode;
}

export interface AccordionProps {
  items: AccordionItem[];
  defaultOpen?: number;
}

export function Accordion({ items, defaultOpen = 0 }: AccordionProps) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="aero-accordion">
      {items.map((it, i) => (
        <div key={i} className="aero-acc-item" data-open={open === i}>
          <div className="aero-acc-head" onClick={() => setOpen((o) => (o === i ? -1 : i))}>
            <span>{it.title}</span>
            <span className="aero-acc-caret">▼</span>
          </div>
          {open === i && <div className="aero-acc-body">{it.body}</div>}
        </div>
      ))}
    </div>
  );
}
