// packages/vue/src/controls/Check.vue
<script setup lang="ts">
const props = defineProps<{ label?: string; indeterminate?: boolean; disabled?: boolean }>();
const model = defineModel<boolean>({ default: false });

function toggle() {
  if (props.disabled) return;
  model.value = !model.value;
}
</script>

<template>
  <label
    :style="{
      display: 'inline-flex',
      alignItems: 'center',
      gap: '10px',
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.5 : 1,
      color: 'var(--t-text)',
    }"
  >
    <div class="aero-check" :data-checked="model" :data-indeterminate="!model && !!indeterminate" @click="toggle" />
    <span v-if="label" class="aero-text-shadow" :style="{ fontSize: '14px' }">{{ label }}</span>
  </label>
</template>

// packages/react/src/controls/Check.tsx
import { useState } from "react";
import type { ReactNode } from "react";

export interface CheckProps {
  label?: ReactNode;
  defaultChecked?: boolean;
  checked?: boolean;
  indeterminate?: boolean;
  onChange?: (checked: boolean) => void;
  disabled?: boolean;
}

export function Check({ label, defaultChecked = false, checked, indeterminate = false, onChange, disabled }: CheckProps) {
  const [internal, setInternal] = useState(defaultChecked);
  const isControlled = checked !== undefined;
  const on = isControlled ? checked : internal;

  const toggle = () => {
    if (disabled) return;
    const next = !on;
    if (!isControlled) setInternal(next);
    onChange?.(next);
  };

  return (
    <label
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 10,
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.5 : 1,
        color: "var(--t-text)",
      }}
    >
      <div className="aero-check" data-checked={on} data-indeterminate={!on && indeterminate} onClick={toggle} />
      {label != null && (
        <span className="aero-text-shadow" style={{ fontSize: 14 }}>
          {label}
        </span>
      )}
    </label>
  );
}
