// packages/vue/src/chrome/Breadcrumb.vue
<script setup lang="ts">
defineProps<{ parts: string[] }>();
</script>

<template>
  <div class="aero-breadcrumb">
    <template v-for="(p, i) in parts" :key="i">
      <span v-if="i === parts.length - 1" class="aero-breadcrumb-current">{{ p }}</span>
      <a v-else href="#" @click.prevent>{{ p }}</a>
      <span v-if="i !== parts.length - 1" class="aero-breadcrumb-sep">›</span>
    </template>
  </div>
</template>

// packages/react/src/chrome/Breadcrumb.tsx
import { Fragment } from "react";

export interface BreadcrumbProps {
  parts: string[];
}

export function Breadcrumb({ parts }: BreadcrumbProps) {
  return (
    <div className="aero-breadcrumb">
      {parts.map((p, i) => {
        const last = i === parts.length - 1;
        return (
          <Fragment key={i}>
            {last ? (
              <span className="aero-breadcrumb-current">{p}</span>
            ) : (
              <a href="#" onClick={(e) => e.preventDefault()}>
                {p}
              </a>
            )}
            {!last && <span className="aero-breadcrumb-sep">›</span>}
          </Fragment>
        );
      })}
    </div>
  );
}
