// packages/react/src/controls/Select.tsx
import { useEffect, useRef, useState } from "react";

export interface SelectProps {
  options: string[];
  defaultValue?: string;
  value?: string;
  placeholder?: string;
  width?: number | string;
  onChange?: (value: string) => void;
}

export function Select({ options, defaultValue, value, placeholder = "Choose…", width, onChange }: SelectProps) {
  const [open, setOpen] = useState(false);
  const [internal, setInternal] = useState<string | null>(defaultValue ?? null);
  const isControlled = value !== undefined;
  const current = isControlled ? value : internal;
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const close = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  const pick = (opt: string) => {
    if (!isControlled) setInternal(opt);
    onChange?.(opt);
    setOpen(false);
  };

  return (
    <div ref={ref} className="aero-select" data-open={open} style={{ width }}>
      <div className="aero-select-trigger" onClick={() => setOpen((o) => !o)}>
        <span style={{ opacity: current ? 1 : 0.6 }}>{current || placeholder}</span>
        <span className="aero-select-caret">▼</span>
      </div>
      {open && (
        <div className="aero-menu">
          {options.map((opt) => (
            <div key={opt} className="aero-menu-item" data-selected={current === opt} onClick={() => pick(opt)}>
              {current === opt && <span style={{ fontSize: 11 }}>✓</span>}
              {opt}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// packages/vue/src/controls/Select.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";

withDefaults(defineProps<{ options: string[]; placeholder?: string; width?: number | string }>(), {
  placeholder: "Choose…",
});
const model = defineModel<string>();

const open = ref(false);
const root = ref<HTMLDivElement | null>(null);

function pick(opt: string) {
  model.value = opt;
  open.value = false;
}
function onDocClick(e: MouseEvent) {
  if (root.value && !root.value.contains(e.target as Node)) open.value = false;
}

onMounted(() => document.addEventListener("mousedown", onDocClick));
onBeforeUnmount(() => document.removeEventListener("mousedown", onDocClick));
</script>

<template>
  <div ref="root" class="aero-select" :data-open="open" :style="{ width: typeof width === 'number' ? `${width}px` : width }">
    <div class="aero-select-trigger" @click="open = !open">
      <span :style="{ opacity: model ? 1 : 0.6 }">{{ model || placeholder }}</span>
      <span class="aero-select-caret">▼</span>
    </div>
    <div v-if="open" class="aero-menu">
      <div
        v-for="opt in options"
        :key="opt"
        class="aero-menu-item"
        :data-selected="model === opt"
        @click="pick(opt)"
      >
        <span v-if="model === opt" :style="{ fontSize: '11px' }">✓</span>
        {{ opt }}
      </div>
    </div>
  </div>
</template>
