// packages/react/src/controls/Tags.tsx
import { useState } from "react";

export interface TagsProps {
  defaultTags?: string[];
  placeholder?: string;
  onChange?: (tags: string[]) => void;
}

export function Tags({ defaultTags = [], placeholder = "Add tag…", onChange }: TagsProps) {
  const [tags, setTags] = useState<string[]>(defaultTags);
  const [draft, setDraft] = useState("");

  const commit = (next: string[]) => {
    setTags(next);
    onChange?.(next);
  };

  const add = () => {
    const t = draft.trim();
    if (t && !tags.includes(t)) commit([...tags, t]);
    setDraft("");
  };

  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>
      {tags.map((t) => (
        <span key={t} className="aero-tag">
          {t}
          <button className="aero-tag-x" onClick={() => commit(tags.filter((x) => x !== t))}>
            ✕
          </button>
        </span>
      ))}
      <input
        className="aero-input"
        style={{ width: 110, padding: "6px 12px", fontSize: 12 }}
        placeholder={placeholder}
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") add();
        }}
      />
    </div>
  );
}

// packages/vue/src/controls/Tags.vue
<script setup lang="ts">
import { ref } from "vue";

withDefaults(defineProps<{ placeholder?: string }>(), { placeholder: "Add tag…" });
const model = defineModel<string[]>({ default: () => [] });

const draft = ref("");

function add() {
  const t = draft.value.trim();
  if (t && !model.value.includes(t)) model.value = [...model.value, t];
  draft.value = "";
}
function remove(tag: string) {
  model.value = model.value.filter((x) => x !== tag);
}
</script>

<template>
  <div :style="{ display: 'flex', flexWrap: 'wrap', gap: '8px', alignItems: 'center' }">
    <span v-for="t in model" :key="t" class="aero-tag">
      {{ t }}
      <button class="aero-tag-x" @click="remove(t)">✕</button>
    </span>
    <input
      class="aero-input"
      :style="{ width: '110px', padding: '6px 12px', fontSize: '12px' }"
      :placeholder="placeholder"
      v-model="draft"
      @keydown.enter="add"
    />
  </div>
</template>
