// packages/react/src/chrome/Dock.tsx
import type { ReactNode } from "react";

export interface DockItem {
  glyph: ReactNode;
  label?: string;
  onClick?: () => void;
}

export interface DockProps {
  items: DockItem[];
}

export function Dock({ items }: DockProps) {
  return (
    <div className="aero-dock">
      {items.map((it, i) => (
        <div className="aero-dock-item" key={i} title={it.label} onClick={it.onClick}>
          {it.glyph}
        </div>
      ))}
    </div>
  );
}

// packages/vue/src/chrome/Dock.vue
<script setup lang="ts">
export interface DockItem {
  glyph: string;
  label?: string;
}

defineProps<{ items: DockItem[] }>();
const emit = defineEmits<{ select: [index: number] }>();
</script>

<template>
  <div class="aero-dock">
    <div v-for="(it, i) in items" :key="i" class="aero-dock-item" :title="it.label" @click="emit('select', i)">{{ it.glyph }}</div>
  </div>
</template>
