// packages/react/src/display/Table.tsx
import type { ReactNode } from "react";

export interface TableProps {
  columns: string[];
  rows: ReactNode[][];
}

export function Table({ columns, rows }: TableProps) {
  return (
    <table className="aero-table">
      <thead>
        <tr>
          {columns.map((c) => (
            <th key={c}>{c}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>
            {r.map((cell, j) => (
              <td key={j}>{cell}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// packages/vue/src/display/Table.vue
<script setup lang="ts">
defineProps<{ columns: string[]; rows: (string | number)[][] }>();
</script>

<template>
  <table class="aero-table">
    <thead>
      <tr>
        <th v-for="c in columns" :key="c">{{ c }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(r, i) in rows" :key="i">
        <td v-for="(cell, j) in r" :key="j">{{ cell }}</td>
      </tr>
    </tbody>
  </table>
</template>
